name: Kotlin CI
on:
  workflow_dispatch:
    inputs:
      branch:
        description: '选择要构建的分支 (main, beta)'
        required: true
        default: 'beta'
        type: choice
        options:
          - main
          - beta
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files in current directory
        run: ls -la

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Add jks file
        run: |
          set -e
          echo "${{ secrets.SIGN_KEY }}" > ./encoded_key
          if base64 -d -i encoded_key > keystore.jks; then
            echo "Successfully decoded and created keystore.jks"
          else
            echo "Failed to decode keystore.jks"
            exit 1
          fi
          rm encoded_key

      - name: Decode SIGNING_PROPERTIES
        run: |
          echo "${{ secrets.SIGNING_PROPERTIES }}" > ./encoded_signing_properties
          if base64 -d -i encoded_signing_properties > signing.properties; then
            echo "Successfully decoded signing properties"
          else
            echo "Failed to decode signing properties"
            exit 1
          fi
          rm encoded_signing_properties

      - name: Set signing properties as environment variables
        run: |
          store_file=$(grep 'storeFile=' signing.properties | cut -d'=' -f2 | tr -d '\r\n')
          store_password=$(grep'storePassword=' signing.properties | cut -d'=' -f2 | tr -d '\r\n')
          key_alias=$(grep 'keyAlias=' signing.properties | cut -d'=' -f2 | tr -d '\r\n')
          key_password=$(grep 'keyPassword=' signing.properties | cut -d'=' -f2 | tr -d '\r\n')
          echo "STORE_FILE=$store_file" >> $GITHUB_ENV
          echo "STORE_PASSWORD=$store_password" >> $GITHUB_ENV
          echo "KEY_ALIAS=$key_alias" >> $GITHUB_ENV
          echo "KEY_PASSWORD=$key_password" >> $GITHUB_ENV

      - name: Add SHORT_SHA Environment Variable
        id: short-sha
        shell: bash
        run: echo "short_sha=`git rev-parse --short HEAD`" >> $GITHUB_ENV

      - name: Build with Gradle (Release)
        if: inputs.branch =='main'
        env:
          VERSION_CODE: ${{ github.run_number }}
          STORE_FILE: ${{ env.STORE_FILE }}
          STORE_PASSWORD: ${{ env.STORE_PASSWORD }}
          KEY_ALIAS: ${{ env.KEY_ALIAS }}
          KEY_PASSWORD: ${{ env.KEY_PASSWORD }}
        run: ./gradlew :tv:assembleRelease

      - name: Build with Gradle (Dev)
        if: (inputs.branch == 'beta' || inputs.branch == 'dev')
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          VERSION_CODE: ${{ github.run_number }}
          STORE_FILE: ${{ env.STORE_FILE }}
          STORE_PASSWORD: ${{ env.STORE_PASSWORD }}
          KEY_ALIAS: ${{ env.KEY_ALIAS }}
          KEY_PASSWORD: ${{ env.KEY_PASSWORD }}
        run: ./gradlew :tv:assembleRelease --warning-mode=all

      - name: Upload Artifact
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: tv-android.apk
          path: tv/build/outputs/apk/release/*.apk

      - name: Move Metadata (Dev)
        if: github.event_name == 'workflow_dispatch' && (inputs.branch == 'beta' || inputs.branch == 'dev')
        run: |
          mv tv/build/outputs/apk/original/release/output-metadata.json tv/build/outputs/apk/release/output-metadata.json

      - name: Move Metadata (Release)
        if: github.event_name == 'workflow_dispatch' && inputs.branch =='main'
        run: |
          mv tv/build/outputs/apk/original/release/output-metadata.json tv/build/outputs/apk/release/output-metadata.json

      - name: Read apk output metadata
        if: github.event_name == 'workflow_dispatch'
        id: apk-meta-release
        uses: juliangruber/read-file-action@v1
        with:
          path: tv/build/outputs/apk/release/output-metadata.json

      - name: Parse apk infos
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "info_version_code=${{ fromJson(steps.apk-meta-release.outputs.content).elements[0].versionCode }}" >> $GITHUB_ENV
          echo "info_version_name=${{ fromJson(steps.apk-meta-release.outputs.content).elements[0].versionName }}" >> $GITHUB_ENV

      - name: Create Tag
        if: github.event_name == 'workflow_dispatch'
        run: |
          tag="v${{ env.info_version_name }}"
          # 检查标签是否已存在
          if git rev-parse $tag >/dev/null 2>&1; then
            echo "Tag $tag already exists, skipping creation"
          else
            git tag $tag
            git push origin $tag
          fi

      - name: Publish Release
        if: github.event_name == 'workflow_dispatch' && inputs.branch =='main'
        uses: softprops/action-gh-release@v2
        with:
          files: tv/build/outputs/apk/release/*.apk
          make_latest: true
          tag_name: "v${{ env.info_version_name }}"
          generate_release_notes: true

      - name: Publish Pre-Release
        if: github.event_name == 'workflow_dispatch' && (inputs.branch == 'beta' || inputs.branch == 'dev')
        uses: softprops/action-gh-release@v2
        with:
          files: tv/build/outputs/apk/release/*.apk
          generate_release_notes: true
          prerelease: true
          tag_name: "v${{ env.info_version_name }}"  